include("algo/AEFA.jl")
include("algo/AEFA_struct.jl")
include("algo/AEO.jl")
include("algo/AFT.jl")
include("algo/AHA.jl")
include("algo/ALA.jl")
include("algo/ALO.jl")
include("algo/AOArithmetic.jl")
include("algo/APO.jl")
include("algo/ARO.jl")
include("algo/AVOA.jl")
include("algo/BES.jl")
include("algo/BKA.jl")
include("algo/BO.jl")
include("algo/BOA.jl")
# include("algo/CFOA.jl")
include("algo/ChOA.jl")
include("algo/CO.jl")
include("algo/CoatiOA.jl")
include("algo/COOT.jl")
include("algo/CSBO.jl")
include("algo/DBO.jl")
include("algo/DDAO.jl")
include("algo/DMOA.jl")
include("algo/DO.jl")
include("algo/DSO.jl")
include("algo/ECO.jl")
include("algo/EDO.jl")
include("algo/ElkHO.jl")
include("algo/EO.jl")
include("algo/ESC.jl")
include("algo/ETO.jl")
include("algo/FLA.jl")
include("algo/FLoodA.jl")
include("algo/FOX.jl")
# include("algo/FPA.jl")
include("algo/GazelleOA.jl")
include("algo/GBO.jl")
include("algo/GEA.jl")
include("algo/GJO.jl")
include("algo/GKSO.jl")
include("algo/GNDO.jl")
include("algo/GO.jl")
include("algo/GOA.jl")
include("algo/GTO.jl")
include("algo/GWO.jl")
include("algo/HBA.jl")
include("algo/HBO.jl")
include("algo/HEOA.jl")
include("algo/HGS.jl")
include("algo/HGSO.jl")
include("algo/HHO.jl")
include("algo/HikingOA.jl")
include("algo/HO.jl")
include("algo/HorseOA.jl")

include("algo/INFO.jl")
include("algo/IVYA.jl")
include("algo/Jaya.jl")
include("algo/JS.jl")
include("algo/LCA.jl")
include("algo/LFD.jl")
include("algo/LPO.jl")
include("algo/MossGO.jl")
include("algo/MountainGO.jl")
include("algo/MPA.jl")
include("algo/MRFO.jl")
include("algo/MVO.jl")
include("algo/OOA.jl")
include("algo/ParrotO.jl")
include("algo/PDO.jl")
include("algo/PKO.jl")
include("algo/PLO.jl")
include("algo/POA.jl")
include("algo/PoliticalO.jl")
include("algo/PumaO.jl")
include("algo/QIO.jl")
include("algo/RBMO.jl")
include("algo/RFO.jl")
include("algo/ROA.jl")
include("algo/RSA.jl")
include("algo/RSO.jl")
include("algo/RUN.jl")
include("algo/SBO.jl")
include("algo/SBOA.jl")
include("algo/SCHO.jl")
include("algo/SeaHO.jl")
include("algo/SFOA.jl")
include("algo/SHO.jl")
include("algo/SMA.jl")
include("algo/SnowOA.jl")
include("algo/SO.jl")
include("algo/SparrowSA.jl")
include("algo/STOA.jl")
include("algo/SupplyDO.jl")
include("algo/TLBO.jl")
include("algo/TLCO.jl")
include("algo/TOC.jl")
include("algo/TSA.jl")
include("algo/TTAO.jl")
include("algo/WHO.jl")
include("algo/WO.jl")
include("algo/WOA.jl")
include("algo/WSO.jl")
include("algo/WUTP.jl")
include("algo/YDSE.jl")
include("algo/ZOA.jl")
##
include("utils/Chung_Reynolds.jl")
include("utils/initialization.jl")
##
dim = 30
max_iter = 1000
npop = 50
lb = -100
ub = 100
tlt = "Chung Reynolds"
i = 1
#
BestPosition, BestValue, ConvergenceCurve = AEFA(npop, max_iter, lb, ub, dim, Chung_Reynolds)
println("BestValue: ", BestPosition)