include("AEFA.jl")
include("AEO.jl")
include("AFT.jl")
include("AHA.jl")
include("ALO.jl")
include("AOArithmetic.jl")
include("APO.jl")
include("ARO.jl")
include("AVOA.jl")
include("BES.jl")
include("BKA.jl")
include("BO.jl")
include("BOA.jl")
include("ChOA.jl")
include("CO.jl")
include("CoatiOA.jl")
include("COOT.jl")
include("CSBO.jl")
include("DBO.jl")
include("DDAO.jl")
include("DMOA.jl")
include("DO.jl")
include("DSO.jl")
include("ECO.jl")
include("EDO.jl")
include("ElkHO.jl")
include("EO.jl")
include("ETO.jl")
include("FLA.jl")
include("FLoodA.jl")
include("FOX.jl")
# include("FPA.jl")
include("GazelleOA.jl")
include("GBO.jl")
include("GEA.jl")
include("GJO.jl")
include("GKSO.jl")
include("GNDO.jl")
include("GO.jl")
include("GOA.jl")
include("GTO.jl")
include("GWO.jl")
include("HBA.jl")
include("HBO.jl")
include("HGS.jl")
include("HGSO.jl")
include("HHO.jl")
include("HikingOA.jl")
include("HO.jl")
include("HorseOA.jl")

include("INFO.jl")
include("IVYA.jl")
include("Jaya.jl")
include("JS.jl")
include("LCA.jl")
include("LFD.jl")
include("LPO.jl")
include("MossGO.jl")
include("MountainGO.jl")
include("MPA.jl")
include("MRFO.jl")
include("MVO.jl")
include("OOA.jl")
##
include("Chung_Reynolds.jl")
include("initialization.jl")
##
dim = 30
Max_iteration = 1000
SearchAgents_no = 50
lb = -100
ub = 100
tlt = "Chung Reynolds"
i = 1
#
BestPosition, BestValue, ConvergenceCurve = OOA(SearchAgents_no, Max_iteration, lb, ub, dim, Chung_Reynolds)
println("BestValue: ", BestPosition)